# Generated by Django 3.0.5 on 2020-04-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Onnettomuus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tunniste', models.IntegerField()),
                ('vuosi', models.IntegerField()),
                ('kuukausi', models.IntegerField()),
                ('kuolleet', models.IntegerField()),
                ('loukkaantuneet', models.IntegerField()),
                ('tunti', models.IntegerField()),
                ('pvm', models.DateField(null=True)),
                ('onluokka', models.IntegerField()),
                ('osallkm', models.IntegerField()),
                ('raj', models.IntegerField()),
                ('pinta', models.IntegerField()),
                ('valo', models.IntegerField()),
                ('saa', models.IntegerField()),
                ('kuntano', models.IntegerField()),
                ('kunta', models.CharField(max_length=100)),
                ('todnop', models.IntegerField()),
                ('lampo', models.IntegerField()),
            ],
        ),
    ]
