# Generated by Django 3.0.5 on 2020-04-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onnettomuus',
            old_name='kuukausi',
            new_name='Kk',
        ),
        migrations.RenameField(
            model_name='onnettomuus',
            old_name='kuntano',
            new_name='Kuntasel',
        ),
        migrations.RenameField(
            model_name='onnettomuus',
            old_name='kuolleet',
            new_name='Kuolleet',
        ),
        migrations.RenameField(
            model_name='onnettomuus',
            old_name='lampo',
            new_name='Lampotila',
        ),
        migrations.RenameField(
            model_name='onnettomuus',
            old_name='loukkaantuneet',
            new_name='Loukkaant',
        ),
        migrations.RenameField(
            model_name='onnettomuus',
            old_name='raj',
            new_name='Nopraj',
        ),
        migrations.RenameField(
            model_name='onnettomuus',
            old_name='todnop',
            new_name='Nopsuunoik',
        ),
        migrations.RenameField(
            model_name='onnettomuus',
            old_name='onluokka',
            new_name='Onluokka',
        ),
        migrations.RenameField(
            model_name='onnettomuus',
            old_name='tunniste',
            new_name='Onnett_id',
        ),
        migrations.RenameField(
            model_name='onnettomuus',
            old_name='osallkm',
            new_name='Osallkm',
        ),
        migrations.RenameField(
            model_name='onnettomuus',
            old_name='pinta',
            new_name='Pinta',
        ),
        migrations.RenameField(
            model_name='onnettomuus',
            old_name='pvm',
            new_name='Pvm',
        ),
        migrations.RenameField(
            model_name='onnettomuus',
            old_name='saa',
            new_name='Saa',
        ),
        migrations.RenameField(
            model_name='onnettomuus',
            old_name='tunti',
            new_name='Tunti',
        ),
        migrations.RenameField(
            model_name='onnettomuus',
            old_name='valo',
            new_name='Valoisuus',
        ),
        migrations.RenameField(
            model_name='onnettomuus',
            old_name='vuosi',
            new_name='Vuosi',
        ),
    ]
