# Generated by Django 3.0.5 on 2020-04-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanta', '0004_auto_20200404_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onnettomuus',
            name='Osallkm',
        ),
    ]
