# Generated by Django 3.0.5 on 2020-04-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanta', '0005_remove_onnettomuus_osallkm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onnettomuus',
            name='Lampotila',
            field=models.IntegerField(null=True),
        ),
    ]
